spring:
  profiles:
    active: development

---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: passdb

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE