version: '3'

services:
  customerServiceDB:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passdb    
    ports:
    - 3306:3306
  customerServiceDBadminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080
  customerService:
    image: suffragium/customer-service:0.0.1
    environment:
      DB_HOSTNAME: customerServiceDB
      DB_PORT: 3306
      DB_DATABASE: mysql
      DB_USER: root
      DB_PASS: passdb
    depends_on:
      - customerServiceDB
    ports:
      - 8080:8080